version: "3.1"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp_dev
      MYSQL_PASSWORD: wp_dev
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_USER: wp_dev
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  pma:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8888:80
  wordpress:
    image: wordpress
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_dev
      WORDPRESS_DB_PASSWORD: wp_dev
      WORDPRESS_DB_USER: wp_dev
      WORDPRESS_DEBUG: true
    volumes:
      - ./wp:/var/www/html
volumes:
  db: {}
